# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-27 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trucknumber',
            name='overload',
            field=models.FloatField(default=0),
        ),
    ]
